### ISSUE TITLE
Scarb test doesn't show in which file / line failures happened

### ISSUE THREAD

**Issue by feltroidprime** [software-mansion/scarb#1193]
### Problem

Using `scarb test` might return some failures with a reason. 

However is it not showing the file nor the lline where the failure precisely happened. 
For large codebases, it turns out to be very hard to debug. 

For example I have a division by zero error, but my test is using multiple functions with 1000 divisions spread out everywhere. It's hard to find where the problem is coming from. 

### Proposed Solution

Is it possible to add a trace for the error to say " Failure happened in file XXX.Cairo at Line:ABC, reason : Panicked with Blabla" ?

### Notes

Please
thank you

**Comment by mkaput** [comment]
So, you mean you want to see a backtrace of a panic during Cairo code execution? Like this one you get in Rust: 
<img width="1118" alt="image" src="https://github.com/software-mansion/scarb/assets/3450050/fc2632b7-a429-457d-85da-2413e0cf28d4">

---

This feature is called **backtraces** and is actually a subject to be handled by the Cairo VM and Cairo compiler to generate appropriate metadata (debug info).

On the compiler side, the requirements are currently a work in progress as a shared effort by Cairo, Software Mansion and Wallnut teams. But I don't think anything is being done on Cairo VM side.

cc @orizi, but I think we can close this issue as for now because Scarb cannot do anything to help this
