### ISSUE TITLE
Scarb compiles ALL the contracts over and over again if they were not changed

### ISSUE THREAD

**Issue by RealJohnnyTime** [software-mansion/scarb#1247]
### Problem

Every time I run a test (which includes maybe 2-3 smart contracts), Scarb compiles **ALL** the contracts in the project, which takes a lot of time. Even if the contracts haven't changed, it still recompiles them, unlike Foundry & Hardhat, which have caching mechanisms.

Is there a way to prevent Scarb from compiling ALL the contracts when running specific tests?

Any suggestions?

**Comment by mkaput** [comment]
Unfortunately, this is not something we can fix on Scarb level. This behaviour, **incremental compilation**, is to be implemented in the Cairo compiler itself. It's still a low-priority thing, as there are more important things to do right now.

FYI, Foundry/Hardhat can because their relation with `solc` is different, and they have more in-depth knowledge about Solidity source that they compile. Scarb just knows about `src/lib.cairo` and `tests/*.cairo` files, and everything else is done deep within the Cairo compiler.

Closing as this duplicates #588

**Comment by RealJohnnyTime** [comment]
Thanks for the response, and sorry for the duplicate, couldn't find other related issues.
