### ISSUE TITLE
Use scarb metadata config inside the crates config

### ISSUE THREAD

**Issue by wawel37** [software-mansion/scarb#1517]
As for now, we are using the default crates config for Global config [here](https://github.com/software-mansion/scarb/blob/a3c269df994b5b27b5f79210dad34cd82a25480a/extensions/scarb-doc/src/metadata/compilation.rs#L109), but we should put the scarb config here (using `compilation_unit_metadata` probably)

**Comment by wawel37** [comment]
Note: Ask @piotmag769 if it's even necessary to change that

**Comment by piotmag769** [comment]
Doesn't seem needed since the global settings are only used if the settings for package are not there. We do set it for every package though.

https://github.com/software-mansion/scarb/blob/a3c269df994b5b27b5f79210dad34cd82a25480a/extensions/scarb-doc/src/metadata/compilation.rs#L92

You can add a comment about it if you want
