### ISSUE TITLE
Detect missing Starknet target when building a Starknet contract

### ISSUE THREAD

**Issue by milancermak** [software-mansion/scarb#469]
### Problem

I have the most basic Scarb project set up, with only one file (besides `lib.cairo`), `src/basic.cairo`:

```rust
#[starknet::interface]
trait IBasic<TContractState> {
    fn get_value(self: @TContractState) -> u128;
}

#[starknet::contract]
mod Basic {
    #[storage]
    struct Storage {
        value: u128
    }

    #[external(v0)]
    impl IBasicImpl of super::IBasic<ContractState> {
        fn get_value(self: @ContractState) -> u128 {
            self.value.read()
        }
    }
}
```

and Scarb.toml like

```toml
[package]
name = "basic"
version = "0.1.0"
```

When running `scarb build` like this, I get the following error:

```sh
error: Type not found.
 --> basic.cairo:14:38
    impl IBasicImpl of super::IBasic<ContractState> {
                                     ^***********^

error: Type not found.
 --> basic.cairo:15:29
        fn get_value(self: @ContractState) -> u128 {
                            ^***********^

error: Method `read` not found on type "<missing>". Did you import the correct trait and impl?
 --> basic.cairo:16:24
            self.value.read()
                       ^**^


error: could not compile `basic` due to previous error
```

This error changes slightly when I remember (!) to add `[[target.starknet-contract]]` to `Scarb.toml`:

```sh
warn: package `basic` declares `starknet-contract` target, but does not depend on `starknet` package
note: this may cause contract compilation to fail with cryptic errors
help: add dependency on `starknet` to package manifest
 --> Scarb.toml
    [dependencies]
    starknet = ">=2.0.2"

error: Type not found.
 --> basic.cairo:14:38
    impl IBasicImpl of super::IBasic<ContractState> {
                                     ^***********^

error: Type not found.
 --> basic.cairo:15:29
        fn get_value(self: @ContractState) -> u128 {
                            ^***********^

error: Method `read` not found on type "<missing>". Did you import the correct trait and impl?
 --> basic.cairo:16:24
            self.value.read()
                       ^**^


error: could not compile `basic` due to previous error
```

This new error message is better because 1) it clearly describes the problem and 2) suggests a solution ❤️ . Adding the `dependencies` section does indeed fix the problem and my contract compiles.

The problem is I had to remember to use these two Scarb config declarations in the first place. As I don't often create new Scarb packages, it took me a while to do so. At first, I checked my Cairo file for typos and then stared at my terminal for 3 minutes trying to figure out what the problem is.

### Proposed Solution

I have 2 propositions how this could be prevented:

1) Update the default `Scarb.toml` that is created with `scarb --init` to have the necessary declarations for compiling Starknet contracts present, but commented out. I'd wager Scarb is more often than not being used to declare Starknet contract projects, so this should be visible by default.

2) If Scarb is able to detect that a mod in the project is declared as `#[starknet::contract]` (as it did in the second iteration above, once I've added the `[[target.starknet-contract]]` clause, it should run this detection every time and suggest a fix if building a contract throws an error, same as above.

### Notes

```sh
scarb --version
scarb 0.5.2 (f4b62adfb 2023-07-11)
cairo: 2.0.2 (https://crates.io/crates/cairo-lang-compiler/2.0.2)
```

**Comment by mkaput** [comment]
Hey! So this problem is two-fold, as the two solutions that you have proposed. First and foremost, even though Scarb is mostly used for Starknet development, we must keep in mind that core Scarb is core Cairo, and Starknet is an "extension" (hardcoded as for, but UX is maintained). Special conditions that print warnings should be fine though IMHO, though I wonder what @spapinistarkware would say here 😅 

So to address these two problems/solutions separately:
1. That's definitely something we aim for! But in different form, and I've been deprioritizing this totally, maybe that's not good. In essence, we would like to have this mechanism extensible for other scenarios, and thus we thought of making something like #213. That's already an approach popularize by tools like yeoman, cookiecutter etc. But recently I thought if it wouldn't be easier to have something like create-react-app; that would be `scarb create-starknet-contract`. It's all TBD to be honest.
2. The detection part is tricky, because it is totally fine to make a package which you do not intent to build as a contract (i.e. uses `starknet` package but only has `[lib]` target). The warning that you suggest would be misleading in this scenario.

**Comment by milancermak** [comment]
1) Using templates sounds like a good solution. Thought it's cumbersome at first, because I'd had to remember the template name, but I can just search in the shell history, that's fine for me.
2) Sounds difficult 😅

**Comment by mkaput** [comment]
Closing this, because these two problems can be solved by:
1. #213 for creating new project
2. https://github.com/starkware-libs/cairo/issues/3401 for catching if Starknet attributes are used without Starknet package

**Comment by mkaput** [comment]
FYI Forge is working on the template: https://github.com/foundry-rs/starknet-foundry/pull/565
