### ISSUE TITLE
Adding -f flag to help

### ISSUE THREAD

**Issue by gaetbout** [software-mansion/scarb#497]
### Problem

when doing 
```shell
scarb --help
```
The help is missing the flag -f allowing to filter the tests to pick up

### Proposed Solution

Updating the help

**Comment by maciektr** [comment]
The `scarb test` command is not a test runner by itself, but rather delegates work to a testing solution of choice. Scarb comes with preinstalled `scarb cairo-test` extension, which bundles Cairo's native test runner. It is the default test runner used by `scarb test`.

Because of this characteristic, `scarb test --help` does not show help message of `cairo-test`, but rather help for the command that delegates testing to a test runner of choice. You can run `scarb cairo-test --help` to see help message for the  `cairo-test` extension, or `scarb test -- --help` to run your configured test runner with `--help` flag.

Please take a look [at our docs](https://docs.swmansion.com/scarb/docs/testing) for more info on testing with Scarb.

**Comment by mkaput** [comment]
To add on top of what @maciektr said, our idea was that the last two lines in help output will guide users to look up their test runners flags. Do you think it's not clear enough and got you confused? Feedback as always appreciated 😃 

<img width="1082" alt="image" src="https://github.com/software-mansion/scarb/assets/3450050/440f85fe-ca35-4500-8521-861647ec2cac">
