### ISSUE TITLE
Support compilation of no-core main packages

### ISSUE THREAD

**Issue by smonicas** [software-mansion/scarb#619]
### Problem

I was trying to compile the corelib expecting that the `no-core = true` config option would allow that however it crashes on this line due to an index out of bounds in `core_package_component()`. https://github.com/software-mansion/scarb/blob/97c624017ff02c9b84480a5adc0c0bdc09c36bfa/scarb/src/compiler/db.rs#L54-L56
I suspect it's missing some logic to set the corelib to None in case `no-core` is true since this allows to correctly compile it.

### Steps

Run `scarb build` on the corelib.

### Version

```text
0.7.0
```

**Comment by maciektr** [comment]
Hi @smonicas!

We know it is not supported, actually it can even trigger assertions we make (e.g. https://github.com/software-mansion/scarb/blob/97c624017ff02c9b84480a5adc0c0bdc09c36bfa/scarb/src/compiler/compilation_unit.rs#L72C2-L72C2).

What is your use case behind this exactly?

**Comment by smonicas** [comment]
Hi, i just wanted to get the sierra representation for the corelib functions. Since it's already known feel free to close the issue, i can handle it myself. Thank you.

**Comment by mkaput** [comment]
I actually think, we we shouldn’t support that…? Definitely not something our team should urgently engage on, but I’d be quite happy to accept a contribution for this

**Comment by maciektr** [comment]
Yes, this we can accept a PR fixing this. 

### Problem
Compilation with main package that sets `no-core` fails. 

Currently, compilation units are wired to `corelib` package via required component. 
https://github.com/software-mansion/scarb/blob/529865094ea02ea67e77e07f1f0e8161e287f809/scarb/src/compiler/compilation_unit.rs#L69
This and all subsequent usages of this function need to be adjusted so that we allow building `ProjectConfig` without the optional `corelib` field. 
https://github.com/software-mansion/scarb/blob/97c624017ff02c9b84480a5adc0c0bdc09c36bfa/scarb/src/compiler/db.rs#L54-L56

### Notes
- Please make sure that the `corelib` package can be compiled after this changes. 

---

Please leave a comment that you are willing to contribute a PR fixing this issue before starting doing so, in order to avoid having two people working on this independently 😄

**Comment by maciektr** [comment]
Done in https://github.com/software-mansion/scarb/pull/1112
