### ISSUE TITLE
Support casm serialised output 

### ISSUE THREAD

**Issue by maciektr** [software-mansion/scarb#676]
### Problem

As of now,  `lib` target compilation (as opposed to starknet contract targets) is capable of producing CASM artefacts in a textual, human readable format only (equivalent to `sierra-compile` compiler cli). In contrast, starknet contract compilation uses serialisable json format instead. It is possible to define a similar serialisable casm format for non-contract projects as well. This alternative should be supported as an artefact of `lib` target compilation. 

### Proposed solution

- Modify `lib` target properties to allow casm artefact format specification
    - `lib` target properties are defined here: https://github.com/software-mansion/scarb/blob/ba2c45574cf149a2d7422cb7c89aef5a203ec970/scarb/src/compiler/compilers/lib.rs#L18-L22
    - Analogously  to `sierra` artefact, it should allow `casm` and `casm_text` boolean inputs.
    - `casm` should create json serialized artefacts, while `casm-text` should create textual ones.
    - By default both should be disabled.
    - This properties will be available to users as `casm` and `casm-text` keys on `[lib]` object in `Scarb.toml` manifest files.
- Modify `lib` target compiler to produce new artefacts.
    - This compiler abstraction is implemented in this file: https://github.com/software-mansion/scarb/blob/ba2c45574cf149a2d7422cb7c89aef5a203ec970/scarb/src/compiler/compilers/lib.rs#L39
    - Should read properties from previous point and produce artefacts accordingly to user specification.
    - Artefact for serialised output should be written with `.casm.json` extension into the target directory with target name as filename.
    - Artefact for textual output should be written with `.casm` extension into the target directory, with the same name.
- Ensure new artefact type is produced
    - It should be enough to modify this test case https://github.com/software-mansion/scarb/blob/ba2c45574cf149a2d7422cb7c89aef5a203ec970/scarb/tests/build_targets.rs#L72

### Notes
See https://github.com/software-mansion/scarb/pull/637/files for similar change introducing new artefact format.

**Comment by mkaput** [comment]
> * Analogously  to `sierra` artefact, it should allow `casm` and `casm_text` boolean inputs.
> * `casm` should create json serialized artefacts, while `casm-text` should create textual ones.
> * By default both should be disabled.
> * This properties will be available to users as `casm` and `casm-text` keys on `[lib]` object in `Scarb.toml` manifest files.

I'm not entirely sure about this ones; perhaps we should consult this with Ori or Ariel. For CASM it kinda makes sense to still output text as the default, isn't it?

**Comment by rodrigo-pino** [comment]
> I'm not entirely sure about this ones; perhaps we should consult this with Ori or Ariel. For CASM it kinda makes sense to still output text as the default, isn't it?

I personally don't see the point of it since you there is no use for that output. I believe it is just something nice to look at. 

Given the knowledge I have, for casm to make sense it needs to have some metadata that describes it such as Entrypoints, Builtins and Hints that it is using. If it is in something easily parseable format (such as json) it really helps other non-rusty tools.

**Comment by mkaput** [comment]
I've asked Cairo team about this.

**Comment by mkaput** [comment]
OK, discussed privately. Let's make JSON the default, and add `casm-text` option.

**Comment by maciektr** [comment]
Hi @rodrigo-pino !
Are you working on this?

**Comment by rodrigo-pino** [comment]
Hi @maciektr, sorry just did an initial scope analysis gathering what I needed to implement, I found in that search that I will need Sierra metadata as well since in order to made a Cairo 1 runner you require metadata that exists on both Sierra and Casm (but we can make separate PRs for

I haven't implemented much, but be sure I (or someone from the team) will take on this since we do need it at some point in not the far future. If you want to put it backlog or something, I understand. I'll ping you right here as soon as we are ready to take on this!

**Comment by maciektr** [comment]
Sure, I understand completely! I will put it back to backlog, but it's still yours!

**Comment by maciektr** [comment]
Closing as not planned since release of `universal-sierra-compiler` ([software-mansion/universal-sierra-compiler](https://github.com/software-mansion/universal-sierra-compiler)) which should provide support for all different kinds of sierra to casm compilation.
