### ISSUE TITLE
new scarb use old version scarb-cairo-language-server

### ISSUE THREAD

**Issue by script-money** [software-mansion/scarb#921]
### Problem

 I upgraded from version 0.7.0 to the latest version 2.3.1 and found a lot of code error in vscode. I tried various methods but couldn't solve the issue.

![19081700535389_ pic](https://github.com/software-mansion/scarb/assets/74860630/483ac869-8d06-438f-8072-b401a79daca9)

### Notes

Eventually, I found that deleting the following old version files working.

![20351700538758_ pic](https://github.com/software-mansion/scarb/assets/74860630/f4ed7092-0c2b-4003-b05c-9a85d8156f40)

In [document](https://docs.swmansion.com/scarb/download.html#uninstall), I think the program should come with solutions to these problems by default, or the documentation should mention it.

### Version

```text
scarb 2.3.1 (0c8def3aa 2023-10-31)
cairo: 2.3.1 (https://crates.io/crates/cairo-lang-compiler/2.3.1)
sierra: 1.3.0
```

**Comment by mkaput** [comment]
Hey! Our installation script definitely has not created these files; we always only created the `.local/bin/scarb` file. You must have created them yourself, so that's not something up to the script.

If you have an idea what we can improve in our docs or the installation script, always feel free to submit a PR 🙂
